spring:
  application:
    name: gateway-service
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: ${KEYCLOAK_ISSUER_URI:http://localhost:${KEYCLOAK_PORT:18081}/realms/power-predict}

server:
  port: 8080

powerpredict:
  system-service:
    base-url: http://localhost:8081
  plant-service:
    base-url: http://localhost:8082
  monitor-service:
    base-url: http://localhost:8084
  forecast-service:
    base-url: http://localhost:8085
  inference-service:
    base-url: http://localhost:8003
  auth:
    local-debug-enabled: ${LOCAL_DEBUG_AUTH_ENABLED:true}
    local-token: local-demo-token
